{
  "status": "fail",
  "tests": [
    {
      "message": "The expression `not ( all_fail : leap_year ( 2015 ) )` was expected to return `true`, but it returned `false` instead",
      "name": "year not divisible by 4 in common year",
      "status": "fail",
      "test_code": "'1_year_not_divisible_by_4_in_common_year_test_'() ->\n    {\"year not divisible by 4 in common year\",\n     {16,\n      fun() ->\n             begin\n                 fun() ->\n                        X__T = is_process_alive(self()),\n                        case not all_fail:leap_year(2015) of\n                            X__T ->\n                                ok;\n                            X__V ->\n                                error({assert,\n                                       [{module, all_fail_tests},\n                                        {line, 16},\n                                        {expression,\n                                         \"not ( all_fail : leap_year ( \"\n                                         \"2015 ) )\"},\n                                        {expected, true},\n                                        case not X__T of\n                                            X__V ->\n                                                {value, false};\n                                            _ ->\n                                                {not_boolean, X__V}\n                                        end]})\n                        end\n                 end()\n             end\n      end}}.\n"
    },
    {
      "message": "The expression `not ( all_fail : leap_year ( 1970 ) )` was expected to return `true`, but it returned `false` instead",
      "name": "year divisible by 2, not divisible by 4 in common year",
      "status": "fail",
      "test_code": "'2_year_divisible_by_2_not_divisible_by_4_in_common_year_test_'() ->\n    {\"year divisible by 2, not divisible by 4 in common year\",\n     {21,\n      fun() ->\n             begin\n                 fun() ->\n                        X__T = is_process_alive(self()),\n                        case not all_fail:leap_year(1970) of\n                            X__T ->\n                                ok;\n                            X__V ->\n                                error({assert,\n                                       [{module, all_fail_tests},\n                                        {line, 21},\n                                        {expression,\n                                         \"not ( all_fail : leap_year ( \"\n                                         \"1970 ) )\"},\n                                        {expected, true},\n                                        case not X__T of\n                                            X__V ->\n                                                {value, false};\n                                            _ ->\n                                                {not_boolean, X__V}\n                                        end]})\n                        end\n                 end()\n             end\n      end}}.\n"
    },
    {
      "message": "The expression `all_fail : leap_year ( 1996 )` was expected to return `true`, but it returned `false` instead",
      "name": "year divisible by 4, not divisible by 100 in leap year",
      "status": "fail",
      "test_code": "'3_year_divisible_by_4_not_divisible_by_100_in_leap_year_test_'() ->\n    {\"year divisible by 4, not divisible by 100 in leap year\",\n     {26,\n      fun() ->\n             begin\n                 fun() ->\n                        X__T = is_process_alive(self()),\n                        case all_fail:leap_year(1996) of\n                            X__T ->\n                                ok;\n                            X__V ->\n                                error({assert,\n                                       [{module, all_fail_tests},\n                                        {line, 26},\n                                        {expression,\n                                         \"all_fail : leap_year ( 1996 )\"},\n                                        {expected, true},\n                                        case not X__T of\n                                            X__V ->\n                                                {value, false};\n                                            _ ->\n                                                {not_boolean, X__V}\n                                        end]})\n                        end\n                 end()\n             end\n      end}}.\n"
    },
    {
      "message": "The expression `all_fail : leap_year ( 1960 )` was expected to return `true`, but it returned `false` instead",
      "name": "year divisible by 4 and 5 is still a leap year",
      "status": "fail",
      "test_code": "'4_year_divisible_by_4_and_5_is_still_a_leap_year_test_'() ->\n    {\"year divisible by 4 and 5 is still a leap year\",\n     {31,\n      fun() ->\n             begin\n                 fun() ->\n                        X__T = is_process_alive(self()),\n                        case all_fail:leap_year(1960) of\n                            X__T ->\n                                ok;\n                            X__V ->\n                                error({assert,\n                                       [{module, all_fail_tests},\n                                        {line, 31},\n                                        {expression,\n                                         \"all_fail : leap_year ( 1960 )\"},\n                                        {expected, true},\n                                        case not X__T of\n                                            X__V ->\n                                                {value, false};\n                                            _ ->\n                                                {not_boolean, X__V}\n                                        end]})\n                        end\n                 end()\n             end\n      end}}.\n"
    },
    {
      "message": "The expression `not ( all_fail : leap_year ( 2100 ) )` was expected to return `true`, but it returned `false` instead",
      "name": "year divisible by 100, not divisible by 400 in common year",
      "status": "fail",
      "test_code": "'5_year_divisible_by_100_not_divisible_by_400_in_common_year_test_'() ->\n    {\"year divisible by 100, not divisible by 400 in common year\",\n     {36,\n      fun() ->\n             begin\n                 fun() ->\n                        X__T = is_process_alive(self()),\n                        case not all_fail:leap_year(2100) of\n                            X__T ->\n                                ok;\n                            X__V ->\n                                error({assert,\n                                       [{module, all_fail_tests},\n                                        {line, 36},\n                                        {expression,\n                                         \"not ( all_fail : leap_year ( \"\n                                         \"2100 ) )\"},\n                                        {expected, true},\n                                        case not X__T of\n                                            X__V ->\n                                                {value, false};\n                                            _ ->\n                                                {not_boolean, X__V}\n                                        end]})\n                        end\n                 end()\n             end\n      end}}.\n"
    },
    {
      "message": "The expression `not ( all_fail : leap_year ( 1900 ) )` was expected to return `true`, but it returned `false` instead",
      "name": "year divisible by 100 but not by 3 is still not a leap year",
      "status": "fail",
      "test_code": "'6_year_divisible_by_100_but_not_by_3_is_still_not_a_leap_year_test_'() ->\n    {\"year divisible by 100 but not by 3 is still not a leap year\",\n     {41,\n      fun() ->\n             begin\n                 fun() ->\n                        X__T = is_process_alive(self()),\n                        case not all_fail:leap_year(1900) of\n                            X__T ->\n                                ok;\n                            X__V ->\n                                error({assert,\n                                       [{module, all_fail_tests},\n                                        {line, 41},\n                                        {expression,\n                                         \"not ( all_fail : leap_year ( \"\n                                         \"1900 ) )\"},\n                                        {expected, true},\n                                        case not X__T of\n                                            X__V ->\n                                                {value, false};\n                                            _ ->\n                                                {not_boolean, X__V}\n                                        end]})\n                        end\n                 end()\n             end\n      end}}.\n"
    },
    {
      "message": "The expression `all_fail : leap_year ( 2000 )` was expected to return `true`, but it returned `false` instead",
      "name": "year divisible by 400 is leap year",
      "status": "fail",
      "test_code": "'7_year_divisible_by_400_is_leap_year_test_'() ->\n    {\"year divisible by 400 is leap year\",\n     {45,\n      fun() ->\n             begin\n                 fun() ->\n                        X__T = is_process_alive(self()),\n                        case all_fail:leap_year(2000) of\n                            X__T ->\n                                ok;\n                            X__V ->\n                                error({assert,\n                                       [{module, all_fail_tests},\n                                        {line, 45},\n                                        {expression,\n                                         \"all_fail : leap_year ( 2000 )\"},\n                                        {expected, true},\n                                        case not X__T of\n                                            X__V ->\n                                                {value, false};\n                                            _ ->\n                                                {not_boolean, X__V}\n                                        end]})\n                        end\n                 end()\n             end\n      end}}.\n"
    },
    {
      "message": "The expression `all_fail : leap_year ( 2400 )` was expected to return `true`, but it returned `false` instead",
      "name": "year divisible by 400 but not by 125 is still a leap year",
      "status": "fail",
      "test_code": "'8_year_divisible_by_400_but_not_by_125_is_still_a_leap_year_test_'() ->\n    {\"year divisible by 400 but not by 125 is still a leap year\",\n     {50,\n      fun() ->\n             begin\n                 fun() ->\n                        X__T = is_process_alive(self()),\n                        case all_fail:leap_year(2400) of\n                            X__T ->\n                                ok;\n                            X__V ->\n                                error({assert,\n                                       [{module, all_fail_tests},\n                                        {line, 50},\n                                        {expression,\n                                         \"all_fail : leap_year ( 2400 )\"},\n                                        {expected, true},\n                                        case not X__T of\n                                            X__V ->\n                                                {value, false};\n                                            _ ->\n                                                {not_boolean, X__V}\n                                        end]})\n                        end\n                 end()\n             end\n      end}}.\n"
    },
    {
      "message": "The expression `not ( all_fail : leap_year ( 1800 ) )` was expected to return `true`, but it returned `false` instead",
      "name": "year divisible by 200, not divisible by 400 in common year",
      "status": "fail",
      "test_code": "'9_year_divisible_by_200_not_divisible_by_400_in_common_year_test_'() ->\n    {\"year divisible by 200, not divisible by 400 in common year\",\n     {55,\n      fun() ->\n             begin\n                 fun() ->\n                        X__T = is_process_alive(self()),\n                        case not all_fail:leap_year(1800) of\n                            X__T ->\n                                ok;\n                            X__V ->\n                                error({assert,\n                                       [{module, all_fail_tests},\n                                        {line, 55},\n                                        {expression,\n                                         \"not ( all_fail : leap_year ( \"\n                                         \"1800 ) )\"},\n                                        {expected, true},\n                                        case not X__T of\n                                            X__V ->\n                                                {value, false};\n                                            _ ->\n                                                {not_boolean, X__V}\n                                        end]})\n                        end\n                 end()\n             end\n      end}}.\n"
    }
  ],
  "version": 2
}
